### ISSUE TITLE
[Feature Request] More info for MCPE!

### ISSUE THREAD

**Issue by ghost** [MCAPI-CA/Issues#10]
When I query MCPE servers with http://mcapi.us/server/query?ip=play.avengetech.net&port=19132 it tells me everything but they cache their API which ruins the point. I love mcapi.ca I just wish it displayed all of this info for MCPE servers also.

**Comment by Yive** [comment]
Will look into.

**Comment by DALTONTASTIC** [comment]
By the way I integrated your query API into a PHP Twitter bot script. It allows people to tweet out their server's status. https://github.com/DALTONTASTIC/mctwitterbot

**Comment by Yive** [comment]
Update, MCPE will be getting a lot more data displayed. It was an experiment at first so that's why not much data was displayed.

**Comment by Yive** [comment]
Released in new version.
