### ISSUE TITLE
Using MCAPI For Iran Servers (interanet) Skin API

### ISSUE THREAD

**Issue by XAmiraliX** [MCAPI-CA/Issues#12]
Hey i want to use Skin API for skins restorer for My server in iran And whats bad about this my server in iran can only connect to servers in iran and yea so i cant download any thing from MC API in my server,i was thinking about  a way for this and if its possible We can make a mc api for iran or if its possible we get the data base and use it :smile: i realy want this !

**Comment by RobiRami** [comment]
This is not an issue with this website. Use proxies.
