### ISSUE TITLE
Anything relating to UUIDs doesn't work correctly

### ISSUE THREAD

**Issue by ifvictr** [MCAPI-CA/Issues#15]
All APIs on https://mcapi.ca having to do with UUIDs is not working correctly. This includes the: UUID , Name, and Buycraft APIs. For example, using GET on ` https://mcapi.ca/uuid/player/Yive` should return this (as shown on the site):
```json
{
        "uuid": "da6ab8ee71ad46d29529cf95df6902b9",
        "uuid_formatted": "da6ab8ee-71ad-46d2-9529-cf95df6902b9",
        "name": "Yive"
}
```
but instead returns this:
```json
{
        "uuid": "",
        "uuid_formatted": "----",
        "name": ""
}
```
I have confirmed that this is a problem on MCAPI-CA's end, and not Mojang's API using: [CraftAPI](https://craftapi.com/index) and [MC-API](https://us.mc-api.net/).

**Comment by Yive** [comment]
This is a known issue, it'll be fixed once I get time to fix it.

**Comment by Blamo27** [comment]
Still doesn't work  ? :/

**Comment by Yive** [comment]
It should work now, just gotta wait till all 40 IPs are no longer rate limited by mojang.

**Comment by Blamo27** [comment]
> https://mcapi.ca/SR/?player=Dr_Blamo

**Comment by Blamo27** [comment]
@Yive It was working for few hours but now, It's still bugged :/

**Comment by Yive** [comment]
@Blamo27 yeah some server has been spamming the API with the plugin SkinsRestorer so I am looking into a way to fix this. Trying out to see how well it does with caching of between 10 mins to 1 hour.

**Comment by Blamo27** [comment]
@Yive Okey, thanks for the info.

**Comment by Th3Tr0LLeR** [comment]
@Yive I told you this will happen :D

**Comment by Yive** [comment]
@Th3Tr0LLeR Just look at this, it's insane, all of the requests are getting response code 429 so I think I need to allocate more proxies to the SkinsRestorer api.
![img](https://i.tcpr.ca/HdsYRfC)

**Comment by Th3Tr0LLeR** [comment]
@Yive Uhmhmh, Yeah. For the newest version i am using only that one https://mcapi.ca/name/uuid/da6ab8ee71ad46d29529cf95df6902b9
