### ISSUE TITLE
1.9.4?

### ISSUE THREAD

**Issue by AshourAziz** [MCAPI-CA/Issues#17]
It seems something has changed with bungeecord 1.9.4 I'm not sure but most API's are broken here are a few server examples:
https://mcapi.ca/query/FadeCloud.com/info
https://mcapi.ca/query/spvp.me/info
https://mcapi.ca/query/play.islandclash.com/info

**Comment by Yive** [comment]
It's an issue with BungeeCord only, I can't really do much about it since it seems to be broken in BungeeCord itself. I know it's BungeeCord since I tested LilyPad & that worked.

**Comment by AshourAziz** [comment]
Do you know exactly which versions this is effect?

**Comment by Yive** [comment]
From what I can tell, yes
