### ISSUE TITLE
Send domain when grabbing player count

### ISSUE THREAD

**Issue by SystemUpdate** [MCAPI-CA/Issues#18]
Hello,

When using your API to query a minecraft server it doesn't send the domain if I use a domain like such https://mcapi.ca/query/primehcf.com/info

This is a problem for us as we use DDoS Protection which responds depending on what domain was entered. This shouldn't be too hard to implement

**Comment by Yive** [comment]
Yeah unfortunately the auto SRV detection system doesn't seem to work 100% of the time. I will try to fix it once I finish fixing my PC.

**Comment by Yive** [comment]
Fixed in the new system that'll hopefully be done before october.
