### ISSUE TITLE
The UUID api doesn't work on VB.net or on my web browser

### ISSUE THREAD

**Issue by KareemMAX** [MCAPI-CA/Issues#2]
I want to make a faction to know the model of the player (Steve or Alex)
so I have written this code :
![image](https://cloud.githubusercontent.com/assets/16426366/12220910/eb663146-b78d-11e5-98bc-d46899e1ae70.png)
but the result is empty text
I have tried it also on my web browser and it's the result of the UUID api :
![image](https://cloud.githubusercontent.com/assets/16426366/12220931/82b25fb6-b78e-11e5-928b-4e178e6e7e9b.png)

**Comment by Yive** [comment]
The UUID API has been overloaded for a little while, I will be looking into a way to fix this issue.

**Comment by Plancke** [comment]
Also having this problem, would like to get a fix for this asap since Mojang's API is throttled so hard :(

**Comment by Yive** [comment]
I've started to look into fixing this, but unfortunately that means I will only be able to do a single user at a time.
