### ISSUE TITLE
Error code on rate-limit

### ISSUE THREAD

**Issue by games647** [MCAPI-CA/Issues#20]
After some requests 3-5 or so, I'm getting a null UUID even for [your example](https://mcapi.ca/uuid/player/Yive) which should already be in the cache?

Response
```json
[
{
uuid: null,
id: null,
uuid_formatted: "----",
name: null,
cache: 1465810202,
cache_length: "00:40:13",
proxy_number: "18",
current_time: 1465808029
}
]
```

This makes it impossible to resolve the playername to UUID.

**Comment by Yive** [comment]
yeah unfortunately I am unable to do anything about this, mojang's rate limits are so strict that 64 different IPs wont help.

**Comment by games647** [comment]
Maybe a cache would help and it would be extremely useful for developers if there is a special response code or json component if the server hit the rate-limit.

**Comment by Yive** [comment]
There is already a cache, it caches for between 10 minutes - 1 hour.

**Comment by games647** [comment]
Could I make another suggestion? Currently the API returns a cracked response if the service failed to look it up. Could you maybe add an error code to make sure if a user is really cracked or the service just failed to look it up.

The point is that if I receive a cracked response I cannot be sure if the player is really cracked. So I cannot store it in a database. It means I have to requests cracked usernames multiple times.

**Comment by Yive** [comment]
So instead of the whole stuff that's displayed in the original post above, if that happens you want it to output an error?

**Comment by games647** [comment]
Yes that would very helpful or just an additional property in order to provide backwards compatibility So that applications won't go completely crazy if the parsing failed.

**Comment by Yive** [comment]
Okay, I'll implement that once I log into the server. Even though I highly doubt this will happen again due to fixing the caching.

**Comment by games647** [comment]
Thanks a lot. This makes it then a really useful API. I'll donate some dollars once it's finished. 

Thanks a lot for the service and your effort to keep it running.

**Comment by games647** [comment]
@Yive Is there some kind of donation link? I would like to show a banner or a big text that my plugin ChangeSkin is using your service if the server has rate-limiting issues and it would be great if those user would donate to you in order to say thank you.
