### ISSUE TITLE
Skin api is missing the encoded properties

### ISSUE THREAD

**Issue by games647** [MCAPI-CA/Issues#23]
I noticed that the skin api doesn't included the encoded properties as shown in the example.

When I access the example from this site: https://mcapi.ca/examples/name-api

https://mcapi.ca/name/uuid/da6ab8ee71ad46d29529cf95df6902b9

There will be no encoded data.

**Comment by Yive** [comment]
Unfortunately I had to get rid of it the other day due to the new caching system. Forgot to update the example.

**Comment by games647** [comment]
Couldn't you re add it, because it would be neat to have those data too. While waiting for #3

**Comment by scifi2000** [comment]
I totally support @games647, I would love getting the encoded properties from your api. Perfect for big networks with nick system or similar.
