### ISSUE TITLE
Feature Request - Multiple Server Status

### ISSUE THREAD

**Issue by MrMonkeyPants344** [MCAPI-CA/Issues#26]
Hey,
So I am wanting a feature where I can ping multiple servers and get their stats joined together. For example:

Lobby 1 = 4 Players / 100 Players
Lobby 2 = 15 Players / 100 Players
Lobby 3 = 12 Players / 100 Players

It would ping back = 31 Players / 300 Players.

Thanks and i hope you take this under consiteration.

**Comment by Yive** [comment]
I'll look into adding that into the rewrite.

**Comment by MrMonkeyPants344** [comment]
Thanks, if this is added, I would love to be notifed.

**Comment by Yive** [comment]
Update:

Been doing some testing & here's a result of the test, just thought you might like to know that it's going to happen 😄 

https://gist.github.com/Yive/fbc34015d94340e5cdc8c6bab443f028

**Comment by MrMonkeyPants344** [comment]
Amazing. Can't wait for this!

**Comment by MrMonkeyPants344** [comment]
How is this going?

**Comment by Yive** [comment]
Well multi server support works, but the site is not ready for release, unfortunately I had to put the development of it on hold due to my other site being very broken which required a full rewrite

**Comment by Yive** [comment]
New version released
