### ISSUE TITLE
MCAPI.CA - Minecraft PE Server Query License

### ISSUE THREAD

**Issue by xSuVe** [MCAPI-CA/Issues#27]
Hello,
I was wondering if there is any license avabile for the API.

Thanks!

**Comment by Yive** [comment]
What do you mean license? It's free to use by anyone, you don't need to get any sort of license to use the API.

**Comment by xSuVe** [comment]
Oh ok, but one more question - Is not open source, right?

**Comment by Yive** [comment]
It's not open sourced.
