### ISSUE TITLE
Player avatar showing as steve only with hat.

### ISSUE THREAD

**Issue by macdja38** [MCAPI-CA/Issues#28]
The hat layer shows steve while their is clearly something more to the skin according to the 3d render.
https://mcapi.ca/avatar/2d/DeMoXIX/100/true
https://mcapi.ca/avatar/2d/DeMoXIX/100/false

What those URLs look like at this time.
http://i.imgur.com/xTpFRdw.png

And the players current skin.
https://cdn.discordapp.com/attachments/98169065062825984/218596350844076032/DeMoXIX.png

**Comment by Yive** [comment]
Will look into this, probably a simple cache deletion will fix it.

**Comment by Yive** [comment]
Fixed
