### ISSUE TITLE
add metadata in the skin API

### ISSUE THREAD

**Issue by KareemMAX** [MCAPI-CA/Issues#3]
I saw in [MojangAPI](wiki.vg/Mojang_API) that I can know if the player model is Steve or Alex so I use the "properties_decoded" section in the Skin API but I couldn't find the "metadate" section under the "skin" section so I tried to decode the "properties" value and I saw that:

``` JSON
{
"timestamp":1452552684137,
"profileId":"c054d78ee15a4633be166650c0855efb",
"profileName":"KareemMAX",
"signatureRequired":true,
"textures":{
"SKIN":{
"url":"http://textures.minecraft.net/texture/ad0896c9af67db6b91f332d7542815f64124a8b636e63fc69a6de9ea8bdf13"
,"metadata":{"model":"slim"}
}
}
}
```

but in the "properties_decoded" section I saw that:

``` JSON
"properties_decoded": [
        {
            "timestamp": 1452552684137,
            "profileId": "c054d78ee15a4633be166650c0855efb",
            "profileName": "KareemMAX",
            "textures": {
                "SKIN": {
                    "url": "http:\/\/textures.minecraft.net\/texture\/ad0896c9af67db6b91f332d7542815f64124a8b636e63fc69a6de9ea8bdf13"
                },
                "CAPE": {
                    "url": null
                }
            }
        }
    ]
```

It will be awesome if add this because I won't need to decode the "properties" value every time

**Comment by Yive** [comment]
Added to my TODO list.

**Comment by KareemMAX** [comment]
Ok thanks :smiley:

**Comment by RobiRami** [comment]
I'm also looking for this. I would appreciate it if you add this.

**Comment by Yive** [comment]
This should be added on the new site, just gotta finish my other work first before starting the new mcapi site.

**Comment by games647** [comment]
:+1:

**Comment by Yive** [comment]
Released in new version, will only output if user's skin is set to the slim model.
