### ISSUE TITLE
[Feature request] Get names of multiple UUIDs

### ISSUE THREAD

**Issue by Ich5003** [MCAPI-CA/Issues#31]
Hey,

I would like to see an API where you can simply get the names of multiple UUIDs, f.e. like this:

`https://mcapi.ca/name/uuid/["UUID1","UUID2"...]`

and the respone will look like this:

`[
   {
      "uuid":"UUID1",
      "name":"Name1"
   },
   {
      "uuid":"UUID2",
      "name":"Name2"
   }
...]`

**Comment by Yive** [comment]
Once the database reaches 2 million entries, I'll be looking into something like this. Currently it's at 740k entries after only 14 days of the database being online.
