### ISSUE TITLE
Player has no UUID

### ISSUE THREAD

**Issue by LADBukkit** [MCAPI-CA/Issues#32]
The player 'Sumoplay' has no UUID

https://mcapi.ca/uuid/player/Sumoplay

[
    {
        "uuid": null,
        "id": null,
        "uuid_formatted": "----",
        "name": null,
        "cache": 1478448637,
        "cache_length": "00:55:43",
        "current_time": 1478446481
    }
]

If you write the name in Caps then the response is correct

**Comment by Yive** [comment]
Fixed in new release.
