### ISSUE TITLE
500 error code for querying uuid

### ISSUE THREAD

**Issue by games647** [MCAPI-CA/Issues#33]
Routes I tried:

https://mcapi.ca/profile/Yive

Like from the old API:
https://mcapi.ca/uuid/Yive

Output:
```json
{
    "error": "Something went wrong.",
    "code": 500
}
```

**Comment by JoeZwet** [comment]
https://twitter.com/ItsYive/status/799997625231511552

**Comment by games647** [comment]
@JoeZwet Thanks

**Comment by games647** [comment]
Seems to be fixed now.

**Comment by games647** [comment]
Still happening

**Comment by Yive** [comment]
I'm about to switch over to a new script that'll hopefully be more reliable. Had to rewrite the entire thing, even the database keys will be renamed.
