### ISSUE TITLE
501 error code on querying uuid

### ISSUE THREAD

**Issue by games647** [MCAPI-CA/Issues#34]
Tested with: https://mcapi.ca/profile/games647

Result: 
```json
{
    "error": "Something went terribly wrong. Contact Yive as soon as possible.",
    "status": 501
}
```

https://mcapi.ca/profile/Yive works

**Comment by Yive** [comment]
It's a problem with my proxy, need to wait for my sponsor to fix it.

**Comment by Yive** [comment]
Implemented temporary proxy cooldown to fix these issues for now.

**Comment by games647** [comment]
Currently still not working. Tested 
https://mcapi.ca/uuid/player/Trashtalknb

**Comment by Yive** [comment]
Changed it to be a more realistic error.
