### ISSUE TITLE
Returns Null on Some Servers??

### ISSUE THREAD

**Issue by blakej115** [MCAPI-CA/Issues#36]
I'm trying to grab the Players Online, but it returns null sometimes on these servers specifically:

https://mcapi.ca/query/play.oneshotmc.com/players
https://mcapi.ca/query/play.jartexnetwork.com/players

Any explanation or solution to this? Thanks!

**Comment by Yive** [comment]
Just looked into this & it appears that for some reason my method that handles motd -> html has started outputting malformed utf8 characters. This has been fixed, thank you for letting me know 👍
