### ISSUE TITLE
Unexpected array brackets

### ISSUE THREAD

**Issue by KareemMAX** [MCAPI-CA/Issues#4]
When I tried to deserialize the Name API my program throwed this exception:
>Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Minecraft_skiner.properties' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. 
>To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
>Path 'properties', line 5, position 19.

On this line of code:
```vb.net
Dim NameJson As Name = Newtonsoft.Json.JsonConvert.DeserializeObject(Of Name)(tmpstr)
```
so I tried to remove the array brackets "[", "]" by using this code:
```vb.net
            tmpstr = Replace(tmpstr, "[", "")
            tmpstr = Replace(tmpstr, "]", "")
```
so I think this array brackets are useless and make my [Json library](http://json.net) confused
please remove this or replace it with something better

**Comment by NightDevel** [comment]
lol

**Comment by KasperFranz** [comment]
Now i just took the example of the name API (https://mcapi.ca/name/uuid/221e4bb2797a443f90a3762106a75afc ) with my own uuid.

The property there are returned are real JSON, so it might be at your end you are parsing it wrong.

Which API are you looking up, it might help @Yive to find the issue if there are any?

**Comment by KareemMAX** [comment]
@KasperFranz my problem with those brackets:
```json
{
    "uuid": "221e4bb2797a443f90a3762106a75afc",
    "uuid_formatted": "221e4bb2-797a-443f-90a3-762106a75afc",
    "name": "kasperfranz",
    "properties": ([)
        {
            "name": "textures",
            "value": "eyJ0aW1lc3RhbXAiOjE0NTI2NzE2ODc1MjcsInByb2ZpbGVJZCI6IjIyMWU0YmIyNzk3YTQ0M2Y5MGEzNzYyMTA2YTc1YWZjIiwicHJvZmlsZU5hbWUiOiJrYXNwZXJmcmFueiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTM5NGE5OTE0Yjc3MzRkZTViYzk0OTU4NzZlYWQwYjQxY2Y2OTk5ZWUxZjRhMTE5ZDZmYjg2MDYyNTc2NyJ9fX0=",
            "signature": "QyF25OWysMuFOV\/B2sRTZFBTerO23oc2cKll5mG+BYOSgkBNbnWxcu+tA21UtsT4jf+CzxTJ30J6MtduaTvdAzpMuWRmurLuCi4Y87E6yYCL69puto4naZGgYCpu87IFB+5eeMZpWcEarou2MPhMz1CS\/HjblYnH5+85ev0c+3r1kuH\/ToYnVl0cEVXp+So5L7sAlvjZHMzsf8KBxEc2nXa4UMeX3By4GBgQaNGxRHJ2JPk5P9SiH2591wto7kQu0LQX1AYuu7mZVYRCOASCWLzR726sVCri4Kz5w5kBO8XmYOU2tERHahRioIsVYN9GCF6j8r4QJoQ9shY1QbGprKB97a+WF1RBiN9BW2dgkYp1wqgv4qtNc8Q8UbcQfcOjnDBzl3pIFcI8YYyE7Z\/BtDcS5k58R8S8Cq5zldQi9uI\/c6OTBFvI0DWHeE6Gi9sXAE5s2M4K0AcK0yeildj3QDl3V3yjSUi0+38viGSQHVSg8+yx89vWmDI0nPizAatPgin8zqIbvScvPynI7kSBJjFAM77pRwF8DLmIxJIw6SxjVzmiqT426q1LFagKZD5KbWburE49RSFeX5Z9pvG1zb7W6yo+k7iMSp6ar8+mfTM4VMNsxoOW6kdNccxUpNbI4eTZ1Tqw0ElGbcw76SbXj8ci\/k03EtFimc6inTjfXbM="
        }
    (]),
    "properties_decoded": ([)
        {
            "timestamp": 1452671687527,
            "profileId": "221e4bb2797a443f90a3762106a75afc",
            "profileName": "kasperfranz",
            "textures": {
                "SKIN": {
                    "url": "http:\/\/textures.minecraft.net\/texture\/e394a9914b7734de5bc9495876ead0b41cf6999ee1f4a119d6fb860625767"
                },
                "CAPE": {
                    "url": null
                }
            }
        }
    (]),
    "cache": 1452671850
}
```
I am using [Json.Net API](http://json.net)

**Comment by KareemMAX** [comment]
When I removed this brackets it works fine
I am not Json professional but I think there is no need to use array brackets like this

**Comment by KasperFranz** [comment]
The square brackets are for defining it is an array, this is the proper way to do it.

And you are sure you are doing it as described in the documentation of the that specific plugin?
(their  examples include []

as [] is valid arrays, in properties it's possible to have multiple items (correct me if i'm wrong @Yive )

**Comment by Yive** [comment]
I'm not sure what it'd be like in VB.NET, but this is what it'd be like in PHP for your data.

```php
$data["properties_decoded"][0]["textures"]["SKIN"]["url"]
```

**Comment by KareemMAX** [comment]
The problem was with my code, I have fixed it now.
Thanks
