### ISSUE TITLE
MCApi - Server Query API with Blocked Countries 

### ISSUE THREAD

**Issue by ElieTGM** [MCAPI-CA/Issues#5]
Hello,

My server is blocking MCAPI's integration, being from France, it blocks any other connections to other countries.

Could you possibly give me the MCApi's ip adress so i can normally whitelist it? And if not, how would i fix it?

Thanks!

**Comment by Yive** [comment]
Unfortunately due to previous DDOS attacks in the past, the IP of MCAPI is going to stay private. Well if you're able to, just unblock any IP that's from Los Angeles, USA.

**Comment by KareemMAX** [comment]
You can try this IP : 104.28.24.71
I found it [here](http://viewdns.info/iphistory/?domain=mcapi.ca)
or you can just add mcapi.ca in your whitelist
