### ISSUE TITLE
Name API

### ISSUE THREAD

**Issue by jake44264** [MCAPI-CA/Issues#9]
The Name API is currently not working.
e.g: https://mcapi.ca/name/uuid/5ce9ed6bb8824326a246b23507ce2c97
it all says null.

**Comment by xooxdoo** [comment]
the query API two

**Comment by Yive** [comment]
I do plan to fix the name API & UUID API soon, but unfortunately that might break some plugins.

What's wrong with the query API, @xooxdoo?
